name: 🚀 Deploy website on push

on:
  push:
    branches:
      - main
      
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    environment: staging
    steps:
    - name: Checkout
      uses: actions/checkout@v3.5.2
      
      
    - name: 📂 Sync files
      uses: wallaceer/wp-import-word@v1.2
      with:
        server: 77.83.64.38
        username: fb24.com_jice99s6cve
        password: ${{ secrets.ftp_password }}
        server-dir: /httpdocs/wp-content/uploads/
        exclude: |
          **/.git*
          **/.git*/**
        
